// This file was generated by counterfeiter
package fake_job_service

import (
	"sync"

	"github.com/craigfurman/woodhouse-ci/jobs"
	"github.com/craigfurman/woodhouse-ci/web"
)

type FakeJobService struct {
	FindByIdStub        func(id string) (jobs.Job, error)
	findByIdMutex       sync.RWMutex
	findByIdArgsForCall []struct {
		id string
	}
	findByIdReturns struct {
		result1 jobs.Job
		result2 error
	}
	SaveStub        func(job *jobs.Job) error
	saveMutex       sync.RWMutex
	saveArgsForCall []struct {
		job *jobs.Job
	}
	saveReturns struct {
		result1 error
	}
}

func (fake *FakeJobService) FindById(id string) (jobs.Job, error) {
	fake.findByIdMutex.Lock()
	fake.findByIdArgsForCall = append(fake.findByIdArgsForCall, struct {
		id string
	}{id})
	fake.findByIdMutex.Unlock()
	if fake.FindByIdStub != nil {
		return fake.FindByIdStub(id)
	} else {
		return fake.findByIdReturns.result1, fake.findByIdReturns.result2
	}
}

func (fake *FakeJobService) FindByIdCallCount() int {
	fake.findByIdMutex.RLock()
	defer fake.findByIdMutex.RUnlock()
	return len(fake.findByIdArgsForCall)
}

func (fake *FakeJobService) FindByIdArgsForCall(i int) string {
	fake.findByIdMutex.RLock()
	defer fake.findByIdMutex.RUnlock()
	return fake.findByIdArgsForCall[i].id
}

func (fake *FakeJobService) FindByIdReturns(result1 jobs.Job, result2 error) {
	fake.FindByIdStub = nil
	fake.findByIdReturns = struct {
		result1 jobs.Job
		result2 error
	}{result1, result2}
}

func (fake *FakeJobService) Save(job *jobs.Job) error {
	fake.saveMutex.Lock()
	fake.saveArgsForCall = append(fake.saveArgsForCall, struct {
		job *jobs.Job
	}{job})
	fake.saveMutex.Unlock()
	if fake.SaveStub != nil {
		return fake.SaveStub(job)
	} else {
		return fake.saveReturns.result1
	}
}

func (fake *FakeJobService) SaveCallCount() int {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	return len(fake.saveArgsForCall)
}

func (fake *FakeJobService) SaveArgsForCall(i int) *jobs.Job {
	fake.saveMutex.RLock()
	defer fake.saveMutex.RUnlock()
	return fake.saveArgsForCall[i].job
}

func (fake *FakeJobService) SaveReturns(result1 error) {
	fake.SaveStub = nil
	fake.saveReturns = struct {
		result1 error
	}{result1}
}

var _ web.JobService = new(FakeJobService)
